spring.application.name=Sistema de Facturacion y Inventario para Restaurantes
spring.profiles.active =dev
server.port=5050
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/restaurante}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:admin}
# Se omite driver-class-name y database-platform para que Spring Boot los autodetecte según la URL de conexión (soporta MySQL y PostgreSQL)
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.format_sql=true

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true